In [1]:
import torch
import numpy as np


In [2]:
print("="*50)
print("Tensor/Array Creation (1D, 2D, 3D)")
print("="*50)

# 1D
np_1d = np.array([1, 2, 3])
py_1d = torch.tensor([1, 2, 3])
print(f"NumPy 1D:\n{np_1d}")
print(f"PyTorch 1D:\n{py_1d}\n")

# 2D
np_2d = np.array([[1, 2, 3], [4, 5, 6]])
py_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"NumPy 2D:\n{np_2d}")
print(f"PyTorch 2D:\n{py_2d}\n")

# 3D
np_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
py_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"NumPy 3D:\n{np_3d}")
print(f"PyTorch 3D:\n{py_3d}\n")

Tensor/Array Creation (1D, 2D, 3D)
NumPy 1D:
[1 2 3]
PyTorch 1D:
tensor([1, 2, 3])

NumPy 2D:
[[1 2 3]
 [4 5 6]]
PyTorch 2D:
tensor([[1, 2, 3],
        [4, 5, 6]])

NumPy 3D:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
PyTorch 3D:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])



In [3]:
print("="*50)
print("Basic Operations (Element-wise)")
print("="*50)
    
a_np = np.array([10, 20, 30])
b_np = np.array([1, 2, 3])
a_torch = torch.tensor([10, 20, 30])
b_torch = torch.tensor([1, 2, 3])

print(f"Add (NP): {a_np + b_np}")
print(f"Add (Torch): {a_torch + b_torch}")
print(f"Sub (NP): {a_np - b_np}")
print(f"Sub (Torch): {a_torch - b_torch}")
print(f"Mul (NP): {a_np * b_np}")
print(f"Mul (Torch): {a_torch * b_torch}")
print(f"Div (NP): {a_np / b_np}")
print(f"Div (Torch): {a_torch / b_torch}\n")

print("="*50)
print("Dot Product and Matrix Multiplication")
print("="*50)

mat1_np = np.array([[1, 2], [3, 4]])
mat2_np = np.array([[1, 0], [0, 1]])
mat1_th = torch.tensor([[1, 2], [3, 4]])
mat2_th = torch.tensor([[1, 0], [0, 1]])

# Dot product (vectors)
vec1 = np.array([1, 2])
vec2 = np.array([3, 4])
print(f"Dot (NP): {np.dot(vec1, vec2)}")
print(f"Dot (Torch): {torch.dot(torch.tensor([1, 2]), torch.tensor([3, 4]))}")

# Matrix Multiplication
print(f"MatMul (NP) @:\n{mat1_np @ mat2_np}")
print(f"MatMul (Torch) @:\n{mat1_th @ mat2_th}")
print(f"MatMul (Torch) matmul:\n{torch.matmul(mat1_th, mat2_th)}\n")

print("="*50)
print("Indexing and Slicing")
print("="*50)

x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Original Tensor:\n{x}")
print(f"Slice [0, :]: {x[0, :]}")
print(f"Slice [:, 1]: {x[:, 1]}")

Basic Operations (Element-wise)
Add (NP): [11 22 33]
Add (Torch): tensor([11, 22, 33])
Sub (NP): [ 9 18 27]
Sub (Torch): tensor([ 9, 18, 27])
Mul (NP): [10 40 90]
Mul (Torch): tensor([10, 40, 90])
Div (NP): [10. 10. 10.]
Div (Torch): tensor([10., 10., 10.])

Dot Product and Matrix Multiplication
Dot (NP): 11
Dot (Torch): 11
MatMul (NP) @:
[[1 2]
 [3 4]]
MatMul (Torch) @:
tensor([[1, 2],
        [3, 4]])
MatMul (Torch) matmul:
tensor([[1, 2],
        [3, 4]])

Indexing and Slicing
Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Slice [0, :]: tensor([1, 2, 3])
Slice [:, 1]: tensor([2, 5, 8])


In [4]:
# Boolean Masking
mask = x > 5
print(f"Boolean Mask (x > 5):\n{mask}")
print(f"Selected Elements: {x[mask]}\n")

print("="*50)
print("Reshaping and View")
print("="*50)

reshapable = torch.arange(12)
print(f"Original (0-11): {reshapable}")


Boolean Mask (x > 5):
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
Selected Elements: tensor([6, 7, 8, 9])

Reshaping and View
Original (0-11): tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [5]:
# View vs Reshape
# .view() requires contiguous tensor, .reshape() handles it automatically (might copy)
viewed = reshapable.view(3, 4)
reshaped_th = reshapable.reshape(3, 4)
reshaped_np = np.arange(12).reshape(3, 4)

print(f"View (3, 4):\n{viewed}")
print(f"Torch Reshape (3, 4):\n{reshaped_th}")
print(f"NumPy Reshape (3, 4):\n{reshaped_np}")


View (3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Torch Reshape (3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
NumPy Reshape (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
# Squeeze / Unsqueeze
t = torch.zeros(2, 1, 2)
print(f"\nTensor shape: {t.shape}")
squeezed = t.squeeze()
print(f"Squeezed shape: {squeezed.shape}") # (2, 2)
unsqueezed = squeezed.unsqueeze(0)
print(f"Unsqueezed (dim 0) shape: {unsqueezed.shape}") # (1, 2, 2)
print()



Tensor shape: torch.Size([2, 1, 2])
Squeezed shape: torch.Size([2, 2])
Unsqueezed (dim 0) shape: torch.Size([1, 2, 2])



In [ ]:
print("="*50)
print("Broadcasting")
print("="*50)

a_bc = torch.tensor([[1], [2], [3]]) # (3, 1)
b_bc = torch.tensor([1, 2, 3])       # (3,) -> broadcasts to (1, 3)

result_bc = a_bc + b_bc
print(f"Shape (3, 1) + (3,): Result shape {result_bc.shape}")
print(f"Result:\n{result_bc}\n")


Broadcasting
Shape (3, 1) + (3,): Result shape torch.Size([3, 3])
Result:
tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

In-place vs Out-of-place
Original: tensor([1, 2, 3])
Out-of-place add(10): tensor([11, 12, 13])
Original after out-of-place: tensor([1, 2, 3])
In-place add_(10): tensor([11, 12, 13])


In [9]:
print("="*50)
print("In-place vs Out-of-place")
print("="*50)

t_inplace = torch.tensor([1, 2, 3])
print(f"Original: {t_inplace}")

# Out of place
t_new = t_inplace.add(10)
print(f"Out-of-place add(10): {t_new}")
print(f"Original after out-of-place: {t_inplace}")

# In place
t_inplace.add_(10)
print(f"In-place add_(10): {t_inplace}")



In-place vs Out-of-place
Original: tensor([1, 2, 3])
Out-of-place add(10): tensor([11, 12, 13])
Original after out-of-place: tensor([1, 2, 3])
In-place add_(10): tensor([11, 12, 13])
